name = "Quarto"
uuid = "d7167be5-f61b-4dc9-b75c-ab62374668c5"
authors = ["JJ Allaire <jj@rstudio.com>"]
version = "1.0.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1.5"
YAML = "0.4.3"